import { readFile } from "fs/promises";
import path from "path";
import { NextResponse } from "next/server";

// Media lives outside /public (see media-storage.ts) since Next.js only
// serves public/ files that existed at build time, not ones written later
// by the running server. This route streams them from disk instead.
const MEDIA_DIR = path.join(process.cwd(), "data", "uploads");

const MIME_BY_EXT: Record<string, string> = {
  webp: "image/webp",
  mp4: "video/mp4",
  webm: "video/webm",
  mov: "video/quicktime",
};

// Filenames are always server-generated by storeMediaAttachment (uuid + a
// known extension) — reject anything that doesn't match that exact shape
// before it ever touches the filesystem.
const SAFE_FILENAME = /^[0-9a-f-]{36}\.(webp|mp4|webm|mov)$/;

export async function GET(_request: Request, context: { params: Promise<{ filename: string }> }) {
  const { filename } = await context.params;

  if (!SAFE_FILENAME.test(filename)) {
    return new NextResponse("Not found", { status: 404 });
  }

  const ext = filename.slice(filename.lastIndexOf(".") + 1);
  const mimeType = MIME_BY_EXT[ext];

  try {
    const data = await readFile(path.join(MEDIA_DIR, filename));
    return new NextResponse(new Uint8Array(data), {
      headers: {
        "Content-Type": mimeType,
        "Cache-Control": "public, max-age=31536000, immutable",
      },
    });
  } catch {
    return new NextResponse("Not found", { status: 404 });
  }
}
